service: cors-proxy

frameworkVersion: ">=2.43 <3.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  region: ap-northeast-1
  stage: v1

package:
  patterns:
    - '!.*'
    - '!src/proxy.test.js'

functions:
  proxy:
    handler: src/proxy.handler
    events:
      - http:
          path: proxy
          method: GET
          integration: lambda-proxy
