service: cors-proxy

frameworkVersion: ">=3.34 <4.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  region: ap-northeast-1
  stage: v1
  versionFunctions: false
  deploymentBucket:
    name: geolonia-slsdeploymentbucket-${self:provider.region}

package:
  patterns:
    - '!.*'
    - '!src/proxy.test.js'

functions:
  proxy:
    handler: src/proxy.handler
    events:
      - http:
          path: proxy
          method: GET
          integration: lambda-proxy
